sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 7.2
  - 7.3

env:
  - MONGODB_SERVER=127.0.0.1:27017

services:
  - mongodb

before_install:
  - pecl channel-update pecl.php.net
  - pecl install -f mongodb-1.5.2

script:
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]]; then make test-coveralls; else make test; fi
